# Generated by Django 6.0.3 on 2026-04-03 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=200, verbose_name='Nombre del Paciente')),
                ('cama', models.CharField(max_length=50, verbose_name='Cama / Servicio')),
                ('tipo_examen', models.CharField(choices=[('TORCH', 'Panel TORCH'), ('HIDATIDOSIS', 'Hidatidosis'), ('IRAG', 'IRAG'), ('OTRO', 'Otro (Especificar en notas)')], max_length=50, verbose_name='Tipo de Examen')),
                ('estado', models.CharField(choices=[('SOLICITADO', '🔴 Pendiente / Solicitado'), ('TOMADO', '🟡 Muestra Tomada'), ('ENVIADO', '🔵 Enviado a LIMA/DIRESA'), ('RESULTADO', '🟢 Resultado Recibido')], default='SOLICITADO', max_length=20, verbose_name='Estado de la Muestra')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Solicitud')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Observaciones / Justificación')),
                ('medico_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Médico Solicitante')),
            ],
            options={
                'verbose_name': 'Orden de Examen',
                'verbose_name_plural': 'Órdenes de Exámenes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
