# Generated by Django 6.0.3 on 2026-04-03 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Examen')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Disponible para solicitar?')),
            ],
            options={
                'verbose_name': 'Catálogo de Examen',
                'verbose_name_plural': 'Catálogo de Exámenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='ordenexamen',
            name='tipo_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tracking.catalogoexamen', verbose_name='Tipo de Examen'),
        ),
    ]
