# Generated by Django 6.0.3 on 2026-04-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_catalogoexamen_alter_ordenexamen_tipo_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='archivo_resultado',
            field=models.FileField(blank=True, null=True, upload_to='resultados_pdf/', verbose_name='PDF del Resultado'),
        ),
    ]
