# Generated by Django 6.0.3 on 2026-04-06 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_ordenexamen_archivo_resultado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='laboratorista_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='laboratorista_resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='laboratorista_toma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tomas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
