# Generated by Django 6.0.3 on 2026-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_ordenexamen_laboratorista_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Envio'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='fecha_resultado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Resultado'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='fecha_toma',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Toma'),
        ),
    ]
