# Generated by Django 6.0.3 on 2026-04-16 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_ordenexamen_fecha_envio_ordenexamen_fecha_resultado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogoexamen',
            options={'ordering': ['nombre'], 'verbose_name': 'Catalogo de Examen', 'verbose_name_plural': 'Catalogo de Examenes'},
        ),
        migrations.AlterModelOptions(
            name='ordenexamen',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Orden de Examen', 'verbose_name_plural': 'Ordenes de Examenes'},
        ),
        migrations.AlterField(
            model_name='catalogoexamen',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Disponible para solicitar'),
        ),
        migrations.AlterField(
            model_name='ordenexamen',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Pendiente / Solicitado'), ('TOMADO', 'Muestra Tomada'), ('ENVIADO', 'Enviado a LIMA/DIRESA'), ('RESULTADO', 'Resultado Recibido')], default='SOLICITADO', max_length=20, verbose_name='Estado de la Muestra'),
        ),
        migrations.AlterField(
            model_name='ordenexamen',
            name='medico_solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Medico Solicitante'),
        ),
        migrations.AlterField(
            model_name='ordenexamen',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones / Justificacion'),
        ),
        migrations.CreateModel(
            name='EventoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CREACION', 'Creacion'), ('EDICION', 'Edicion'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('PDF', 'Resultado PDF')], max_length=20, verbose_name='Tipo de Evento')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Nuevo')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Evento')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tracking.ordenexamen')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Evento de Orden',
                'verbose_name_plural': 'Eventos de Orden',
                'ordering': ['-fecha_evento', '-id'],
            },
        ),
    ]
