# Generated by Django 6.0.3 on 2026-05-21 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_asignar_grupo_medico_a_usuarios_existentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado del tablero'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Eliminacion'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='motivo_eliminacion',
            field=models.TextField(blank=True, verbose_name='Motivo de Eliminacion'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='usuario_eliminacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_eliminadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Elimino'),
        ),
        migrations.AlterField(
            model_name='eventoorden',
            name='tipo_evento',
            field=models.CharField(choices=[('CREACION', 'Creacion'), ('EDICION', 'Edicion'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('PDF', 'Resultado PDF'), ('DESCARGA_PDF', 'Descarga de PDF'), ('ELIMINACION', 'Eliminacion')], max_length=20, verbose_name='Tipo de Evento'),
        ),
        migrations.CreateModel(
            name='IntentoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('intentos_fallidos', models.PositiveIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_intento', models.DateTimeField(auto_now=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'ordering': ['-ultimo_intento'],
                'indexes': [models.Index(fields=['username', 'ip_address'], name='tracking_in_usernam_04752f_idx'), models.Index(fields=['bloqueado_hasta'], name='tracking_in_bloquea_9c3ba3_idx')],
            },
        ),
    ]
