# Generated by Django 6.0.3 on 2026-05-21 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_ordenexamen_eliminado_ordenexamen_fecha_eliminacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CREACION_USUARIO', 'Creacion de usuario'), ('RESET_PASSWORD', 'Reset de contrasena')], max_length=30, verbose_name='Tipo de Evento')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('username_afectado', models.CharField(max_length=150, verbose_name='Usuario Afectado')),
                ('nombre_visible_afectado', models.CharField(blank=True, max_length=150, verbose_name='Nombre Visible Afectado')),
                ('rol_asignado', models.CharField(blank=True, max_length=50, verbose_name='Rol Asignado')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Evento')),
                ('usuario_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Objetivo')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Auditoria de Usuario',
                'verbose_name_plural': 'Auditoria de Usuarios',
                'ordering': ['-fecha_evento', '-id'],
            },
        ),
    ]
